name: Broken Link Check

on:
  push:
    # branches:
    #   - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Serve Files
        run: |
          npm install -g http-server
          http-server &
      - name: Check links for YokohomaMarona home page
        run: npx broken-link-checker http://127.0.0.1:8080/
