name: Broken Link Check

on:
  page_build:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        run: npx broken-link-checker --recursive --filter-level=2 https://trips.htincentives.com/YokohamaMaroma2023/home.html
