name: Broken Link Check

on:
  push:
    # branches:
    #   - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}
          port: 8080
          no-cache: false
          index-files: |
            ["index.html", "index.htm"]
          allowed-methods: |
            ["GET", "HEAD"]
          content-types: |
            {
              "appcache": "text/cache-manifest",
              "css": "text/css",
              "gif": "image/gif",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "txt": "text/plain",
              "xml": "text/xml"
            }
      - name: Check links for YokohomaMarona home page
        run: npx broken-link-checker http://127.0.0.1:8080/YokohamaMaroma2023/home.html
