name: Broken Link Check

on:
  push:
    # branches:
    #   - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start local webserver
        run: npx http-server
      - name: Check links for YokohomaMarona home page
        run: npx broken-link-checker http://localhost:8080/YokohamaMaroma2023/home.html
